### PR TITLE
Update AndroidManifest.xml

### PR DESCRIPTION
**Pull request by guera2022**

### CODE REVIEW

**Comment by Burndem1** [comment]
Duplicate of # #12

**Comment by Burndem1** [comment]
1. > 

- [ ] _termux_

**Comment by jonathandata1** [comment]
You are welcome to fork the repository and modify the source as you would like for your research, but the code base for these samples need to stay the same for others to have the opportunity to fork a clean source as well. Thanks for your contribution. 

If you see any decompilation issues I would be happy to review them

**Comment by Burndem1** [comment]
Hello world

**Pull request closed without merging**
